#!/bin/bash

alias e='emacsclient --no-wait'
alias zshconfig='s ~/.zshrc'
alias finder='open -R'
alias op='openn'
alias s='subl'
alias sn='subl -n'
alias sm='s --project /Users/oguzserbetci/Library/Mobile\ Documents/com~apple~CloudDocs/note-taking.sublime-project'
alias j='tmux new -s jupyter -d; tmux send-keys -t jupyter "cd ~; jupyter lab" C-m'
alias jl='jupyter notebook list'

alias llt='ls -1t | head -5'

alias vim='nvim'
alias wim='vim -c VimwikiIndex'
alias ipython='ipython --TerminalInteractiveShell.editing_mode=vi'
alias ipython3='ipython3 --TerminalInteractiveShell.editing_mode=vi'
alias cleanswp='rm ~/.local/share/nvim/swap/*'
alias d='dirs -v'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# GIT
alias gs='git status -s'
alias ga='git add--interactive'
alias go='git checkout'
alias gc='git clone'

# PYTHON
alias p3='python3'
alias p='python'

# Show/hide hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop='defaults write com.apple.finder CreateDesktop -bool false; killall Finder'
alias showdesktop='defaults write com.apple.finder CreateDesktop -bool true; killall Finder'

# WORKFLOWS
alias doml='open "https://isis.tu-berlin.de/course/view.php?id=8410"; open ~/University/Machine\ Learning\ 1; atom -n ~/University/Machine\ Learning\ 1/exercises'

# FIX
alias ssh='kitty +kitten ssh'
