cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'
tap 'homebrew/science'

brew 'git'
brew 'coreutils'
brew 'R'
brew 'httpie'
brew 'koekeishiya/khd/khd'
brew 'kwm'
brew 'python3'
brew 'git-extras'

cask 'gitup'
cask 'sublime-text3'
cask 'java'
cask 'google-chrome'
cask 'slack'
cask 'zotero'
cask 'appcleaner'
cask 'grammarly'
cask 'intellij-idea'
cask 'dropbox'
cask 'google-drive'
cask 'numi'
cask 'sketch'
cask 'iterm2'
