tap 'homebrew/bundle'
tap 'homebrew/science'
tap 'koekeishiya/kwm'

brew 'git'
brew 'coreutils'
brew 'zsh-completions'
brew 'koekeishiya/khd/khd'
brew 'koekeishiya/kwm/kwm'
brew 'python3'
brew 'antigen'
brew 'git-extras'
brew 'awscli'
brew 'elasticsearch'
brew 'exercism'
brew 'zsh'
brew 'heroku'
brew 'neovim/neovim/neovim'
brew 'fasd'
brew 'peco'
brew 'realpath'
brew 'mackup'

# Fonts
brew 'fonts'

