#!/bin/bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 1

# TILING
chunkc set global_desktop_mode           bsp

chunkc set global_desktop_offset_top     10
chunkc set global_desktop_offset_bottom  10
chunkc set global_desktop_offset_left    10
chunkc set global_desktop_offset_right   10
chunkc set global_desktop_offset_gap     5

chunkc set desktop_padding_step_size     3
chunkc set desktop_gap_step_size         3

chunkc set bsp_spawn_left                1
chunkc set bsp_split_mode                optimal
chunkc set bsp_optimal_ratio             1.2
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            monitor
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc set window_float_topmost          0
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.5

chunkc set mouse_modifier                fn
chunkc set mouse_follows_focus           intrinsic

#chunkc set preselect_border_color        0xffff92d0
#chunkc set preselect_border_width        3
#chunkc set preselect_border_radius       6

# BORDER
#chunkc set focused_border_color          0xff282a36
#chunkc set focused_border_width          4
#chunkc set focused_border_radius         6
#chunkc set focused_border_skip_floating  0

#chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

# NOTE: specify plugins to load when chunkwm starts.
# Set floating apps
chunkc tiling::rule --owner \"System Preferences\" --state float
chunkc tiling::rule --owner Civilisation V --state float

# Force tiling
chunkc tiling::rule --owner "Emacs.*" --state tile
chunkc tiling::rule --owner Emacs --except "^ $" --state tile

# Set roles
chunkc tiling::rule --owner XMind --role AXWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner Anki --role AXStandardWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner Dash --role AXStandardWindow --subrole AXDialog --state tile

# Set floating panes
chunkc tiling::rule --owner iTunes --name \"Mini Player\" --state float
chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner Finder --name iCloud Progress --state float
chunkc tiling::rule --owner Finder --name Info --state float
chunkc tiling::rule --owner \"Keychain Access\" --state float
chunkc tiling::rule --name \"PDF Metadata Retrieval\" --state float

