#!/bin/bash

chunkc core::plugin_dir ~/.chunkwm_plugins
chunkc core::hotload 1

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 5_desktop_mode                float

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     3
chunkc set global_desktop_offset_bottom  3
chunkc set global_desktop_offset_left    3
chunkc set global_desktop_offset_right   3
chunkc set global_desktop_offset_gap     3

chunkc set desktop_padding_step_size     3
chunkc set desktop_gap_step_size         3

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            all
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc set window_float_topmost          0

chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so

chunkc set focused_border_color          0xffffff00
chunkc set focused_border_width          4
chunkc set focused_border_radius         4
# section - window rules

# regex filters (pattern is case sensitive):
#  --owner  | -o  (application name matches pattern)
#  --name   | -n  (window name matches pattern)
#  --except | -e  (window name does not match pattern)

# properties:
#  --state | -s
#   values:
#    float
#    tile

chunkc rule --owner "System Preferences" --state tile
chunkc rule --owner Finder --name Copy --state float
