#!/usr/bin/env sh
yabai -m config debug_output on

# global settings
yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   3

# Ubersicht update
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-coffee\"'"
# yabai -m signal --add event=display_changed \
#     action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-coffee\"'"

# window rules
yabai -m rule --add app=Emacs manage=on
yabai -m rule --add app=iTunes title="^Mini" manage=off
yabai -m rule --add app=Stickies manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above
yabai -m rule --add app="^QuickTime Player$" title="Movie Recording" sticky=on layer=above
yabai -m rule --add title="^Install" sticky=on layer=above
yabai -m rule --add app=Firefox title="^Opening" sticky=on layer=above
yabai -m rule --add app=Firefox title="^File Upload" sticky=on layer=above
yabai -m rule --add app="Zotero" title!="^Zotero$" sticky=on layer=above
yabai -m rule --add app="DeepL" title!="^DeepL$" sticky=on layer=above

yabai -m space 1 --label chat
yabai -m space 2 --label music

yabai -m rule --add app=Mail space=^1
yabai -m rule --add app=Messages space=^1
yabai -m rule --add app=Signal space=^1
yabai -m rule --add app=Calendar space=^1
yabai -m rule --add app=Telegram space=^1
yabai -m rule --add app=Spotify space=^2
yabai -m rule --add app="Civilization V" manage=off
yabai -m rule --add app="Civilization VI" manage=off

echo "yabai configuration loaded.."
